/**
 * ZUserGetDetail.java
 *
 * このファイルはWSDLから自動生成されました / [en]-(This file was auto-generated from WSDL)
 * Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java生成器によって / [en]-(by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.)
 */

package mc_style.functions.soap.sap.document.sap_com;

public interface ZUserGetDetail extends java.rmi.Remote {
    public void userGetDetail(mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiagrHolder activitygroups, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapicomremHolder addcomrem, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadfaxHolder addfax, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadpagHolder addpag, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadprtHolder addprt, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadrfcHolder addrfc, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadrmlHolder addrml, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadsmtpHolder addsmtp, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadssfHolder addssf, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadtelHolder addtel, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadtlxHolder addtlx, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadttxHolder addttx, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiaduriHolder adduri, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiadx400Holder addx400, java.lang.String cacheResults, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiusextidheadHolder extidhead, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiusextidpartHolder extidpart, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapigroupsHolder groups, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiparamHolder parameter, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiparam1Holder parameter1, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiprofHolder profiles, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiret2Holder _return, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapircvsysHolder systems, mc_style.functions.soap.sap.document.sap_com.holders.TableOfBapiuclasssysHolder uclasssys, java.lang.String username, mc_style.functions.soap.sap.document.sap_com.holders.Bapiaddr3Holder address, mc_style.functions.soap.sap.document.sap_com.holders.BapialiasHolder alias, mc_style.functions.soap.sap.document.sap_com.holders.BapiuscompHolder company, mc_style.functions.soap.sap.document.sap_com.holders.BapidefaulHolder defaults, mc_style.functions.soap.sap.document.sap_com.holders.BapislockdHolder islocked, mc_style.functions.soap.sap.document.sap_com.holders.BapimoddatHolder lastmodified, mc_style.functions.soap.sap.document.sap_com.holders.BapilogondHolder logondata, mc_style.functions.soap.sap.document.sap_com.holders.BapirefusHolder refUser, mc_style.functions.soap.sap.document.sap_com.holders.BapisncuHolder snc, mc_style.functions.soap.sap.document.sap_com.holders.BapiuclassHolder uclass) throws java.rmi.RemoteException;
}
